services:

  golang-dhcpd:
    #image: golang-dhcpd:latest
    build: .
    user: "1001:1001"  # Run as dhcp user
    command: ['/app/mygodhcpd', '-conf', '/etc/golang-dhcpd/conf.yaml']
    restart: always
    volumes:
      - /etc/golang-dhcpd:/etc/golang-dhcpd:ro
      #- /var/lib/golang-dhcpd:/var/lib/golang-dhcpd
    networks:
      dhcp_net:
        ipv4_address: 192.168.0.2
    hostname: golang-dhcpd

    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /var/lib/golang-dhcpd:noexec,nosuid,size=100m,uid=1001,gid=1001

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'
        reservations:
          memory: 16M
          cpus: '0.1'

networks:
  dhcp_net:
    driver: ipvlan
    driver_opts:
      parent: eth1  # Replace with your host interface name
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
